version = 0.1
[default.deploy.parameters]
stack_name = "flask-lambda-api"
resolve_s3 = true
s3_prefix = "flask-lambda-api"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
